version: "3.8"

services:
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: node-backend
    ports:
      - "3000:3000"
    environment:
      - MONGODB_URI=mongodb+srv://globalstudent:globalstudent@globalstudent.5v1nu9s.mongodb.net/?retryWrites=true&w=majority&appName=globalstudent
      - JWT_SECRET=your_jwt_secret
    depends_on:
      - mongo
    restart: unless-stopped

  frontend:
    build: ./public
    container_name: static-frontend
    ports:
      - "8085:80"
    restart: unless-stopped

  mongo:
    image: mongo:6
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: unless-stopped

volumes:
  mongo-data:
